# Generated by Django 3.1 on 2021-06-20 10:54
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def create_initial_plans(apps, schema_editor):
    Plan = apps.get_model('home.Plan')
    plans = [Plan(name='Free', price=0),
             Plan(name='Standard', price=Decimal(10)),
             Plan(name='Pro', price=Decimal(25))]
    Plan.objects.bulk_create(plans)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at',
                 models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(
                    choices=[('Web', 'Web'), ('Mobile', 'Mobile')],
                    max_length=6)),
                ('framework', models.CharField(choices=[('Django', 'Django'), (
                'React Native', 'React Native')], max_length=12)),
                ('domain_name', models.CharField(blank=True, max_length=50)),
                ('screenshot', models.URLField(blank=True)),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   related_name='apps',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at',
                 models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0,
                                              max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at',
                 models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('app',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='home.app')),
                ('plan',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='home.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_initial_plans,
                             reverse_code=migrations.RunPython.noop)
    ]
